//EXAMPLE ON THIS METHOD OVERLOADING
public class DEMO5									//MAIN CLASS
{
	public static void main(String[]args)
	{
		System.out.println("Sno"+"\t\t"+"Name"+"\t\t"+"Author"+"\t\t"+"Cost");
		BOOKS b1=new BOOKS(101,"C","BALA",99.9);	//CREATING AN OBJECT AND ASSIGNING A REFERENCE AND CALLING CONSTRUCTOR WITH 4ARGS
		b1.showData();
		b1=new BOOKS(102,"C++","PP");				//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE AND CALLING CONSTRUCTOR WITH 3ARGS
		b1.showData();
		b1=new BOOKS(103,"JAVA");					//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE AND CALLING CONSTRUCTOR WITH 2ARGS
		b1.showData();
		b1=new BOOKS(101,"BALA",99.9);				//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE AND CALLING CONSTRUCTOR WITH 3ARGS
		b1.showData();
	}
}

